#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 15 10:39:07 2021

@author: ken
"""
import random as rd

def sim_once(team1,team2):
    score_team1= rd.gauss(team1.points.mean(),team1.points.std())
    score_team2= rd.gauss(team2.points.mean(),team2.points.std())
    score_against_team1= rd.gauss(team1.points_against.mean(),team1.points_against.std())
    score_against_team2= rd.gauss(team2.points_against.mean(),team2.points_against.std())
    final_score_t1 = (score_team1+score_against_team2)/2
    final_score_t2 = (score_team2+score_against_team1)/2
    return (final_score_t1,final_score_t2, final_score_t1 > final_score_t2)
    

def sim_multiple(team1,team2,n=100):
    t1_points = []
    t2_points = []
    w_l = []
    for i in n:
        sim = sim_once(team1,team2)
        t1_points.appennd(sim_once[0])
        t2_points.appennd(sim_once[1])
        t1_points.appennd(sim_once[2])
    return (w_l.sum()/n, t1_points, t2_points, w_l)